// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1775.Pneumatics.subsystems;

import org.usfirst.frc1775.Pneumatics.RobotMap;
import org.usfirst.frc1775.Pneumatics.commands.*;

import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.InterruptHandlerFunction;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Launcher extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final Solenoid releaseSolenoid = RobotMap.launcherReleaseSolenoid;
    private final DigitalInput limitSwitch = RobotMap.launcherLimitSwitch;
    private final SpeedController crankArm = RobotMap.launcherCrankArm;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    public void release() {
    	//crankArm.set(0.5);
    	releaseSolenoid.set(true);
    }
    
    public void resetSolenoid() {
    	releaseSolenoid.set(false);
    }
    
    public void crank() {
    	if (!armCranked()) {
    		crankArm.set(-0.5);
    	}
    }
    
    public void stopCrank() {
    	crankArm.set(0);
    	//releaseSolenoid.set(false);
    }
    
    public boolean armCranked() {
    	return limitSwitch.get();
    }

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new Crank());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
}

